"""observations_tmpl — render boilerplate observations.md skeleton from
captured JSON dumps + nav_graph. Each screen becomes a section with bounds
table, transitions list, and blank `Observed behaviour` / `Notes` subsections
for the writer agent (or human) to fill.

Usage:
    python observations_tmpl.py <feature>                 # prints to stdout
    python observations_tmpl.py <feature> -o obs.md       # writes file
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Iterable

from re_spec_mobile.nav_graph import load as load_graph
from re_spec_mobile.profile_loader import load_profile


def _bounds_of(node: dict[str, Any]) -> str:
    b = node.get("bounds")
    if isinstance(b, dict):
        return f'[{b.get("left", 0)},{b.get("top", 0)}][{b.get("right", 0)},{b.get("bottom", 0)}]'
    if isinstance(b, (list, tuple)) and len(b) == 4:
        return f"[{b[0]},{b[1]}][{b[2]},{b[3]}]"
    return str(b or "")


def _short_class(node: dict[str, Any]) -> str:
    c = node.get("class_name") or node.get("class") or ""
    return c.split(".")[-1] if c else ""


def _iter_nodes(nodes: Iterable[dict[str, Any]]):
    for n in nodes:
        yield n
        kids = n.get("children") or []
        if kids:
            yield from _iter_nodes(kids)


def _row(n: dict[str, Any]) -> str | None:
    text = (n.get("text") or "").strip()
    desc = (n.get("content_description") or n.get("content-desc") or "").strip()
    clickable = bool(n.get("clickable"))
    if not (text or desc or clickable):
        return None
    cls = _short_class(n) or "View"
    bounds = _bounds_of(n)
    clk = "**yes**" if clickable else "no"
    txt = f"`{text}`" if text else ""
    ds = f"`{desc}`" if desc else ""
    return f"| {cls} | `{bounds}` | {clk} | {txt} | {ds} |"


def _fmt_screen(profile, feature: str, capture_label: str, *, screen_id: str,
                phone: dict[str, Any], tree: list, edges: list[dict[str, Any]]) -> str:
    out: list[str] = []
    out.append(f"## {capture_label} {{#{feature}/screen/{capture_label}}}")
    out.append("")
    out.append(f"- **Screen ID**: `{screen_id}`")
    rel_dump = profile.feature_dumps_dir(feature).relative_to(profile.project_root)
    rel_screens = profile.feature_screens_dir(feature).relative_to(profile.project_root)
    out.append(f"- **Dump**: `{rel_dump}/{capture_label}.json` (+ `.xml` projection)")
    out.append(f"- **Screenshot**: `{rel_screens}/{capture_label}.png`")
    activity = phone.get("current_activity", "")
    if activity:
        out.append(f"- **Activity**: `{activity}`")
    out.append("")
    out.append("### Visible elements")
    out.append("")
    out.append("| Class | Bounds | Clickable | Text | Content-desc |")
    out.append("|---|---|---|---|---|")
    for n in _iter_nodes(tree):
        row = _row(n)
        if row:
            out.append(row)
    out.append("")
    if edges:
        out.append("### Observed transitions")
        out.append("")
        for e in edges:
            action = e.get("label") or e.get("action") or ""
            out.append(f"- `{action}` -> `{e['to']}`")
        out.append("")
    out.append("### Observed behaviour")
    out.append("")
    out.append("- _(fill in)_")
    out.append("")
    out.append("### Notes")
    out.append("")
    out.append("- _(fill in)_")
    out.append("")
    out.append("---")
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("feature")
    ap.add_argument("-o", "--out", help="output file; stdout if omitted")
    args = ap.parse_args()

    try:
        profile = load_profile()
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    g = load_graph(args.feature, profile=profile)
    dumps_dir = profile.feature_dumps_dir(args.feature)
    if not dumps_dir.exists():
        print(f"No dumps dir at {dumps_dir}", file=sys.stderr)
        return 1

    label_to_id: dict[str, str] = {}
    for sid, s in g.data.get("screens", {}).items():
        for lbl in s.get("captures", []) or []:
            label_to_id[lbl] = sid
        if s.get("label"):
            label_to_id.setdefault(s["label"], sid)

    out_edges: dict[str, list[dict[str, Any]]] = {}
    for e in g.data.get("edges", []):
        out_edges.setdefault(e["from"], []).append(e)

    sections: list[str] = [
        f"# {profile.app_name} — {args.feature.title()} Raw Observations (auto-draft)",
        "",
        "> **Note**: this file was auto-generated by `observations_tmpl.py`. The bounds",
        "> tables and transitions are mechanical projections of the JSON dumps + nav graph.",
        "> Fill in `Observed behaviour` and `Notes` per screen — the writer agent or human.",
        "",
        "---",
        "",
    ]

    for jpath in sorted(dumps_dir.glob("*.json")):
        label = jpath.stem
        state = json.loads(jpath.read_text(encoding="utf-8"))
        sid = label_to_id.get(label, "?")
        edges = out_edges.get(sid, [])
        sections.append(_fmt_screen(
            profile,
            args.feature,
            label,
            screen_id=sid,
            phone=state.get("phone_state") or {},
            tree=state.get("a11y_tree") or [],
            edges=edges,
        ))

    body = "\n".join(sections)
    if args.out:
        Path(args.out).write_text(body, encoding="utf-8")
        print(f"Wrote {args.out}")
    else:
        try:
            sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[attr-defined]
        except Exception:
            pass
        sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
